# Generated by Django 4.2.6 on 2023-10-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('position_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
                ('position_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('position_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=128)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
                ('employee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('employee_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.department')),
                ('employee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position')),
            ],
        ),
    ]
