# Generated by Django 4.2.6 on 2023-10-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('countries', '0001_initial'),
        ('companies', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField()),
                ('date_in', models.DateField()),
                ('lat_in', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng_in', models.DecimalField(decimal_places=6, max_digits=9)),
                ('check_out', models.TimeField()),
                ('date_out', models.DateField()),
                ('lat_out', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng_out', models.DecimalField(decimal_places=6, max_digits=9)),
                ('schedule_start', models.DateField()),
                ('schedule_end', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('grace_in', models.TimeField(help_text='Начало перерыва')),
                ('grace_out', models.TimeField(help_text='Конец перерыва')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.branch')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.employeeschedule')),
            ],
        ),
    ]
