# Generated by Django 4.2.6 on 2023-10-20 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work_days', models.PositiveIntegerField()),
                ('off_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='workingday',
            name='time_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='workingday',
            name='time_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
