# Generated by Django 4.2.6 on 2023-10-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_scheduleparameters_workingday_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='schedule_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.scheduleparameters'),
        ),
    ]
